version: '3.8'

services:
  node:
    image: node:18
    volumes:
      - .:/home/app:delegated
      - node_modules:/home/app/node_modules
    working_dir: /home/app
    tty: true
    environment:
      - NODE_ENV=development

volumes:
  node_modules:
